### ISSUE TITLE
Use Gnome Tweaks to set wallpaper

### ISSUE THREAD

**Issue by mogenson** [jabossu/GnoMojave#1]
You don't have to overwrite adwaita-timed.xml. You can use [Gnome Tweaks](https://wiki.gnome.org/Apps/Tweaks) to select the animated background from any location.

Also I think that `mojave_dynamic-01.jpeg` should be `mojave-12.jpg` and all subsequent images bumped up by one to put things in the right order.

**Comment by jabossu** [comment]
Thank you for your message. You're absolutly right, but i didnt know that at that time. I learned it afterwards by reading the comments left by noble souls.
